language: python

python:
  - 2.7
  - 3.3

env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.10
    - python: 3.3
      env: DJANGO=1.5.5

branches:
  only:
    - master
    - develop

install:
  - "pip install coverage==3.7"
  - "pip install python-coveralls==2.4.0"
  - "pip install Django==$DJANGO"
  - "pip install -e ."

script:
    coverage run --rcfile=.coverage.rc runtests.py

after_success:
    coveralls --config_file=.coverage.rc --coveralls_yaml=.coveralls.yml
